# Site settings
title: H4XCODE
email: lnc13.lars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Topics are: Politics, Relegion, Software Development, *NIX, Old school gaming and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: looopTheKing
github_username:  looopTools

# Build settings
markdown: kramdown
